name: Push workflow
on:
  push:
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Welcome"
        run: echo "Welcome to push trigger"
  bye-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Bye"
        run: echo "Bye workflow"
